[build-system]

requires = ["setuptools"]
[project]
name = "bntx-extractor"
version = "0.7"
dependencies = ["cython", "astc-decomp-faster", "pillow"]

[project.scripts]
bntx-extractor = "bntx_extract:main"
